#!/usr/bin/env bash
# Download a matching, checksummed olcOS framework without rebuilding it.
# Usage: ./scripts/fetch-framework.sh [v1.0.1]
# GH_REPO=owner/repo overrides the public olcOS release repository.
# --cache-key prints the source fingerprint used by BOTH CI and release.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [ "${1:-}" = "--cache-key" ]; then
  python3 - "$ROOT" <<'PY'
import hashlib
from pathlib import Path
import subprocess
import sys

root = Path(sys.argv[1])
upstream = subprocess.check_output(
    ["git", "-C", str(root / "olcrtc-upstream"), "rev-parse", "HEAD"], text=True
).strip()
files = {root / "scripts/build-framework.sh", root / "scripts/fetch-framework.sh"}
files.update(p for p in (root / "scripts/mobile-shim").rglob("*") if p.is_file())
files.update((root / "gomobile").rglob("*.go"))
files.update((root / "gomobile").rglob("go.mod"))
# go.sum is generated by tidy today. Include it only if committed so a local
# tidy and a fresh checkout resolve to the same key; future lockfiles count.
tracked_sums = subprocess.check_output(
    ["git", "-C", str(root), "ls-files", "--", "gomobile/**/go.sum", "gomobile/go.sum"],
    text=True,
).splitlines()
files.update(root / name for name in tracked_sums)
digest = hashlib.sha256(b"olcos-framework-v2\0" + upstream.encode() + b"\0")
for path in sorted(files):
    digest.update(path.relative_to(root).as_posix().encode() + b"\0")
    digest.update(hashlib.sha256(path.read_bytes()).digest())
print(digest.hexdigest())
PY
  exit 0
fi

if [ "$#" -gt 1 ] || [[ "${1:-}" == -* ]]; then
  echo "usage: $0 [v<version>.<build>] | --cache-key" >&2
  exit 1
fi
REPOSITORY="${GH_REPO:-Hotelk52339/olcos-ios}"
TAG="${1:-}"
for tool in gh unzip python3; do
  command -v "$tool" >/dev/null 2>&1 || { echo "error: $tool is required" >&2; exit 1; }
done
# Default to this checkout's public version, not a possibly incompatible latest.
if [ -z "$TAG" ]; then
  TAG="$(python3 scripts/cut-release.py --dry-run | sed -n 's/^tag: //p')"
fi
[[ "$TAG" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?\.[1-9][0-9]*$ ]] || {
  echo "error: invalid release tag" >&2; exit 1;
}
EXPECTED_KEY="$(bash scripts/fetch-framework.sh --cache-key)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
echo "note: downloading matching framework from $REPOSITORY ($TAG) ..."
gh release download "$TAG" --repo "$REPOSITORY" \
  --pattern Mobile.xcframework.zip --pattern framework-provenance.json \
  --pattern SHA256SUMS --dir "$tmp"

python3 - "$tmp" "$EXPECTED_KEY" <<'PY'
import hashlib
import json
from pathlib import Path, PurePosixPath
import stat
import sys
import zipfile

folder, expected = Path(sys.argv[1]), sys.argv[2]
checksums = {}
for line in (folder / "SHA256SUMS").read_text().splitlines():
    digest, name = line.split(maxsplit=1)
    checksums[name.lstrip("*")] = digest
for name in ("Mobile.xcframework.zip", "framework-provenance.json"):
    actual = hashlib.sha256((folder / name).read_bytes()).hexdigest()
    if checksums.get(name) != actual:
        raise SystemExit(f"error: checksum mismatch for {name}; existing framework untouched")
if json.loads((folder / "framework-provenance.json").read_text()).get("input_sha256") != expected:
    raise SystemExit("error: framework inputs differ from checkout; build with scripts/build-framework.sh")
with zipfile.ZipFile(folder / "Mobile.xcframework.zip") as archive:
    for entry in archive.infolist():
        path = PurePosixPath(entry.filename)
        if (path.is_absolute() or ".." in path.parts or "\\" in entry.filename
                or not path.parts or path.parts[0] != "Mobile.xcframework"
                or stat.S_ISLNK(entry.external_attr >> 16)):
            raise SystemExit("error: unsafe framework archive; existing framework untouched")
    if "Mobile.xcframework/Info.plist" not in archive.namelist():
        raise SystemExit("error: framework Info.plist missing")
PY

unzip -q "$tmp/Mobile.xcframework.zip" -d "$tmp/unpacked"
# Keep the old framework intact until verification and extraction succeed.
mkdir -p App
if [ -e App/Mobile.xcframework ]; then
  mv App/Mobile.xcframework "$tmp/previous.xcframework"
fi
if ! mv "$tmp/unpacked/Mobile.xcframework" App/Mobile.xcframework; then
  [ ! -e "$tmp/previous.xcframework" ] || mv "$tmp/previous.xcframework" App/Mobile.xcframework
  exit 1
fi
echo "done: $ROOT/App/Mobile.xcframework"
echo "next: xcodegen generate --spec project.yml"
